---

- name: Configure Server Power Setting - ForceRestart
  dellemc_change_power_state:
    idrac_ip:   "{{ hostvars[inventory_hostname]['idrac_ip_address'] }}"
    idrac_user: "{{ global_idrac_user }}"
    idrac_password:  "{{ global_idrac_password }}"
    # ForceRestart is applicable for idrac firmware versions above 3.30.30.30
    reset_type: "ForceRestart"

  tags:
    - force-restart
