---

    global_idrac_user: "root"
    global_idrac_password:  "I.am.ghost.47"
    share_name: "192.168.1.63:/samba"
    share_password:  "I.am.ghost.47"
    share_user: "samba"
    share_mnt:  "/mnt/"

...
