---

- name: Install rsync
  yum:
    name: rsync
    state: latest

# Verify ISO
- name: check if Fedora iso exists
  stat:
    path: "{{ iso_fedora_pth }}"
    checksum_algorithm: sha256
  register: iso_path_result2

- name: Verify Fedora ISO Checksum
  fail:
    msg: "It appears the iso checksum does not match.  Please redownload the iso from a known good source and verify the iso_checksum is correct in the invetory file."
  when: iso_path_result2.stat.exists and iso_path_result2.stat.checksum != iso_fedora_checksum
  
- name: Mount content to {{ mnt_pth }}
  mount:
    fstype: iso9660
    state: mounted
    opts: loop
    path: "{{ mnt_pth }}"
    src: "{{ iso_fedora_pth }}"
  when:
    - mnt_pth != ""
  register: mounted

- name: Copy dirs from Fedora iso
  synchronize:
    dest: "{{ tftp_dir }}"
    src:  "{{ mnt_pth }}/"
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Unmount iso from {{ mnt_pth }}
  mount:
    state: absent
    path: "{{ mnt_pth }}"

# Set up packages directory
- name: Create the ISO directory
  file:
    path: "{{ repo_path }}"
    state: directory
    mode: '0755'

- name: Create the Packages directory
  file:
    path: "{{ repo_path }}/Packages"
    state: directory
    mode: '0755'

...