# THIS IS UNFINISHED

--- 
    - 
      connection: local
      gather_facts: false
      hosts: hosts
      name: Booting to Network Operating System image
      tasks: 
        - name: "Booting to Network Operating System image"
          idrac_os_deployment:
            idrac_ip: "{{ idrac_ip }}"
            idrac_password: "{{ global_idrac_password }}"
            idrac_user: "{{ global_idrac_user }}"
            share_name: "{{ playbook_dir }}"
            iso_image: "kickstart.iso"        
            expose_duration: 180
    
          tags:
            - network_iso
